/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atm;

/**
 *
 * @author Admin
 */
public class formDoiMatKhau extends javax.swing.JPanel {

  
private String soTien;
   
    
    public formDoiMatKhau() {
        initComponents(); 
       
    }

    public formDoiMatKhau(String soTien) {
        this.soTien = soTien;
        
                initComponents(); 
               // lbSoDu.setText(soTien);
               
    }

 
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlSodu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlDuoi1 = new javax.swing.JPanel();
        lbNhapmkcu = new javax.swing.JLabel();
        lbNhapmkmoi = new javax.swing.JLabel();
        lbNhapLaimkmoi = new javax.swing.JLabel();
        txtNhapMKcu = new javax.swing.JTextField();
        txtNhapMKmoi = new javax.swing.JTextField();
        txtNhapLaiMKmoi = new javax.swing.JTextField();

        setMinimumSize(new java.awt.Dimension(540, 360));
        setPreferredSize(new java.awt.Dimension(540, 360));
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0};
        layout.rowHeights = new int[] {0, 5, 0};
        setLayout(layout);

        pnlSodu.setBackground(new java.awt.Color(51, 51, 255));
        pnlSodu.setPreferredSize(new java.awt.Dimension(540, 360));
        pnlSodu.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Đổi Mật khẩu");
        pnlSodu.add(jLabel1, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        add(pnlSodu, gridBagConstraints);

        pnlDuoi1.setBackground(new java.awt.Color(255, 255, 255));
        java.awt.GridBagLayout pnlDuoi1Layout = new java.awt.GridBagLayout();
        pnlDuoi1Layout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0};
        pnlDuoi1Layout.rowHeights = new int[] {0, 5, 0, 5, 0};
        pnlDuoi1.setLayout(pnlDuoi1Layout);

        lbNhapmkcu.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbNhapmkcu.setText("Nhập mật khẩu cũ:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        pnlDuoi1.add(lbNhapmkcu, gridBagConstraints);

        lbNhapmkmoi.setText("Nhập mật khẩu mới:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        pnlDuoi1.add(lbNhapmkmoi, gridBagConstraints);

        lbNhapLaimkmoi.setText("Nhập lại mật khẩu mới:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        pnlDuoi1.add(lbNhapLaimkmoi, gridBagConstraints);

        txtNhapMKcu.setText("jTextField1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 7;
        pnlDuoi1.add(txtNhapMKcu, gridBagConstraints);

        txtNhapMKmoi.setText("jTextField2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 7;
        pnlDuoi1.add(txtNhapMKmoi, gridBagConstraints);

        txtNhapLaiMKmoi.setText("jTextField3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 7;
        pnlDuoi1.add(txtNhapLaiMKmoi, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 0.2;
        add(pnlDuoi1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbNhapLaimkmoi;
    private javax.swing.JLabel lbNhapmkcu;
    private javax.swing.JLabel lbNhapmkmoi;
    private javax.swing.JPanel pnlDuoi1;
    private javax.swing.JPanel pnlSodu;
    private javax.swing.JTextField txtNhapLaiMKmoi;
    private javax.swing.JTextField txtNhapMKcu;
    private javax.swing.JTextField txtNhapMKmoi;
    // End of variables declaration//GEN-END:variables
}
