/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atm;

/**
 *
 * @author Admin
 */
public class formSodu extends javax.swing.JPanel {

  
private String soTien;
   
    
    public formSodu() {
        initComponents(); 
       
    }

    public formSodu(String soTien) {
        this.soTien = soTien;
        
                initComponents(); 
                lbSoDu.setText(soTien);
               
    }

 
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlSodu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlDuoi1 = new javax.swing.JPanel();
        lbThongBao = new javax.swing.JLabel();
        lbSoDu = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(540, 360));
        setPreferredSize(new java.awt.Dimension(540, 360));
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0};
        layout.rowHeights = new int[] {0, 5, 0};
        setLayout(layout);

        pnlSodu.setBackground(new java.awt.Color(51, 51, 255));
        pnlSodu.setPreferredSize(new java.awt.Dimension(540, 360));
        pnlSodu.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Vấn tin tài khoản");
        pnlSodu.add(jLabel1, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        add(pnlSodu, gridBagConstraints);

        pnlDuoi1.setBackground(new java.awt.Color(255, 255, 255));
        pnlDuoi1.setLayout(new java.awt.GridBagLayout());

        lbThongBao.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbThongBao.setText("Số dư hiện tại là: ");
        pnlDuoi1.add(lbThongBao, new java.awt.GridBagConstraints());

        lbSoDu.setText("0000000đ");
        pnlDuoi1.add(lbSoDu, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 0.2;
        add(pnlDuoi1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbSoDu;
    private javax.swing.JLabel lbThongBao;
    private javax.swing.JPanel pnlDuoi1;
    private javax.swing.JPanel pnlSodu;
    // End of variables declaration//GEN-END:variables
}
